### ISSUE TITLE
おねむ部屋（仮）

### ISSUE THREAD

**Issue by jankoko** [kokoro-discord/kokoro-document#2]
部屋の名前がそのままルールを表しているので、告知して説明する所はあんまりなさそうな？
このまま運用してみて、重い悩み事等のBOMを持っておねむ部屋に入ってくるなどが
あったらまた書いてみたいと思うのですがどうでしょう

VC設定はルーム人数は5人、位置はお布団の一つ上で考えてます

**Comment by butasan** [comment]
VC人数は４人にしてみました。（まったりお話できる限界の人数かな？）
悩み事の相談で入ってきた場合は「ここは眠気待ちのVCであること」「愚痴部屋へ誘導する」などの対処が考えらます。
