### ISSUE TITLE
社会復帰系VC名

### ISSUE THREAD

**Issue by kokoro-discord** [kokoro-discord/kokoro-document#8]
現在名称：働きたいでござる
これの名称を考えたい。
- 実際に使用する用途も考えたい
- もっと適切な名前があれば
![channel](https://user-images.githubusercontent.com/54024129/63603516-c93e8f80-c604-11e9-838d-b380409db64f.png)

**Comment by butasan** [comment]
用途：就労、就活、就労移行支援、就労継続支援などの話題をじっくりしたいとき
名前：おねむ部屋やお布団の名前がすでにゆるいのでこのままでいいかと

**Comment by kokoro-discord** [comment]
# 用途に関して
了解。

# 名称について
働きたいでござるで来てほしい人が分かるのであれば本issueをクローズしたい。

## 名称決定について
- お布団に関しては、「緩さ」が名前のベースではなく、「利用者」の今までの文化を意識して、決定。
- おねむ部屋に関しては、「利用者」が呼び始めた名称なので、おそらく検討はしていない。
  - 利用者側の定義に沿ってるため、自然と受け入れられたので問題なし

名は体を表すので、これは何をするVCであるかをチャンネル名で表してみてはいかがでしょうか。

**Comment by butasan** [comment]
# 名称について
チャンネル名をそのまま説明にするならこのような感じでしょうか
- 就労・復職・訓練

**Comment by kokoro-discord** [comment]
チャンネル名を変更したので対応済み！
